# 5 Minutes to Credit Wellness — PDF Letter Generator
# AE Labs — (c) 2025 Sean Gilmore / Arden Edge Capital
# AE.CC.001
#
# Converts letter dicts into formatted PDFs using ReportLab.
# Bundles multiple PDFs into a downloadable ZIP.

import io
import zipfile
from datetime import datetime

from reportlab.lib.pagesizes import letter as LETTER_SIZE
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


def _build_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="LetterBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
        spaceAfter=6,
        alignment=TA_LEFT,
    ))
    styles.add(ParagraphStyle(
        name="LetterHeader",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        textColor="grey",
        spaceAfter=2,
    ))
    styles.add(ParagraphStyle(
        name="LetterTitle",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        spaceAfter=12,
    ))
    return styles


def letter_to_pdf(letter: dict, client_name: str = "", client_address: str = "") -> bytes:
    """Convert a single letter dict to PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=LETTER_SIZE,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    styles = _build_styles()
    story = []

    # From address
    if client_name:
        story.append(Paragraph(client_name, styles["LetterHeader"]))
    if client_address:
        story.append(Paragraph(client_address, styles["LetterHeader"]))
    story.append(Spacer(1, 6))

    # Date
    story.append(Paragraph(datetime.utcnow().strftime("%B %d, %Y"), styles["LetterHeader"]))
    story.append(Spacer(1, 12))

    # To address
    bureau = letter.get("bureau", "")
    bureau_address = letter.get("bureau_address", "")
    if bureau:
        story.append(Paragraph(bureau, styles["LetterHeader"]))
    if bureau_address:
        story.append(Paragraph(bureau_address, styles["LetterHeader"]))
    story.append(Spacer(1, 18))

    # Title
    title = letter.get("title", "Dispute Letter")
    story.append(Paragraph(f"<b>Re: {title}</b>", styles["LetterTitle"]))

    # Body — split on newlines, convert to paragraphs
    body = letter.get("body", "")
    for line in body.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
        else:
            # Escape XML special chars for ReportLab
            line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(line, styles["LetterBody"]))

    # Footer
    story.append(Spacer(1, 24))
    story.append(Paragraph(
        "<i>Generated by 5 Minutes to Credit Wellness | AE Labs</i>",
        styles["LetterHeader"],
    ))

    doc.build(story)
    return buf.getvalue()


def letters_to_zip(letters: list[dict], client_name: str = "", client_address: str = "") -> bytes:
    """Bundle multiple letters into a ZIP file. Returns ZIP bytes."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for i, letter in enumerate(letters):
            bureau = letter.get("bureau", "Bureau").replace(" ", "_")
            dtype = letter.get("type", "dispute").replace(" ", "_")
            variant = letter.get("variant", "A")
            filename = f"{i+1:02d}_{bureau}_{dtype}_{variant}.pdf"
            pdf_bytes = letter_to_pdf(letter, client_name, client_address)
            zf.writestr(filename, pdf_bytes)
    return buf.getvalue()
